version: '2'
services:
    avaliacao360israel-app:
        image: avaliacao360israel
        external_links:
            - avaliacao360israel-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/avaliacao360Israel
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avaliacao360israel-postgresql:
        extends:
            file: postgresql.yml
            service: avaliacao360israel-postgresql
